langchain-ai/langgraphjs

langgraph/src/prebuilt/tool_executor.ts
noticed this was missing causing missing nested Traces in Langsmith
Fixes # https://github.com/langchain-ai/langgraphjs/issues/44
=> pass RunnableConfig in ToolExecutor tool.invoke

langgraph/src/prebuilt/chat_agent_executor.ts, langgraph/src/prebuilt/tool_executor.ts
Because the `Tool` abstract class extends the `StructuredTool` abstract class, using a `DynamicStructuredTool` would not be usable in the `ToolExecutor`.
https://api.js.langchain.com/classes/langchain_core_tools.StructuredTool.html 
Fixes #40 
~~**Note:** I did not clone the repo locally or tested that.~~
=> Replace Tool by StructuredTool in tool_executor.ts

langgraph/src/index.ts
This exports `MemorySaver` and `BaseCheckpointSaver`, which allows for custom persistence implementations (e.g. SQLite)
=> Export MemorySaver & BaseCheckpointer

langgraph/src/channels/base.ts, langgraph/src/channels/binop.ts, langgraph/src/tests/pregel.test.ts
The `should handle checkpoints correctly` unit test was initially skipped because it didn't pass. 
This PR fixes the two bugs that were preventing it from passing. 
1. `BinaryOperatorAggregate` Channel did not implement `empty()` (aka - snapshot) correctly. The issue was that the old checkpoint's value was not being saved as the initial value leading to a lossy channel that stored state in correctly 
2. `Checkpoint` was not implemented correctly, because it would only update the checkpoint's channel value if it had never been set before. Updated the code such that it _always_ update's the checkpoint value based on the latest channel value 
Now that these have been fixed, add the checkpointing test back in!
=> Added "should handle checkpoints correctly" Unit Tests + Fix 2 Bugs That Were Preventing Them From Passing

CONTRIBUTING.md, langgraph/src/channels/base.ts, langgraph/src/tests/pregel.test.ts
Based on conversations with @nfcampos yesterday, learned a lot about the underlying behavior of LangGraph 
This information is pretty crucial to be able to contribute meaningfully in this code base, so added this information to the CONTRIBUTING.md 
While I was here, made some flyby changes to help clarify things that I thought were confusing
=> Adds Documentation about Channels, Checkpoints, and Pregel Graphs to `CONTRIBUTING.md`

langgraph/src/prebuilt/tool_executor.ts
The default template in tool_executor is incorrect and has not properly replaced availableToolNamesString.
=> fix: default INVALID_TOOL_MSG_TEMPLATE

.devcontainer/devcontainer.json
This just adds a dev container to the workspace, the same setup as in the langchain-js repo.
While the setup cost of the repo is very low, a dev container reduces it to zero for anyone using VSCode.
=> Add VSCode Dev Container

CONTRIBUTING.md
Just make it one tiny bit easier for people curious about Pregel to read the paper, since the current Google link only goes to ACM which requires access, but CMU provides the paper.
=> Include Pregel PDF link in CONTRIBUTING.md

langgraph/src/graph/state.ts, langgraph/src/tests/graph.test.ts
Fixes a new node key validation for StateGraph.
In the previous implementation, it validated existing nodes instead of new ones.
Python implementation reference: https://github.com/langchain-ai/langgraph/blob/main/langgraph/graph/state.py#L48
=> fix: state graph new node validation

langgraph/src/pregel/index.ts, langgraph/src/tests/pregel.test.ts
Ensure `Channel.subscribeTo(["input"], { key: "key" })` which throws at runtime is a type-error.
=> Type-safety of Channel.subscribeTo

langgraph/package.json, langgraph/src/channels/base.ts, langgraph/src/pregel/index.ts, langgraph/src/pregel/read.ts, langgraph/src/pregel/write.ts, langgraph/src/tests/pregel.test.ts, langgraph/src/utils.ts, package.json, yarn.lock
This PR updates static functions in `pregel/index.ts` to the match the corresponding Python implementation. These functions are used in the core `stream()` and `invoke()` methods of the `Pregel` class.
1. Implement `_shouldInterrupt()` (currently unused).
2. Update `_applyWrites()` to match Python implementation.
3. Remove `_applyWritesFromView()`. Removing the function did not break any tests. Not sure if this needs to be migrated.
4. Update `_prepareNextTasks()` to match Python implementation. Note: The side effect from this function is removed and the calling code is updated to ensure that all existing tests pass.
5. Implement `_localRead()` (replaced old implementation of `read`).
6. Update `ChannelRead` and `ChannelWrite` to extend from `RunnableCallable` (this was a regression).
7. …
=> Update static functions in `pregel/index.ts` to match corresponding Python implementation

langgraph/src/pregel/index.ts, langgraph/src/pregel/types.ts, langgraph/src/tests/pregel.test.ts
`_defaults()` is a new method in the `Pregel` class (Python implementation) that the updated `invoke()` and `stream()` methods depend on.
Reference: https://github.com/langchain-ai/langgraph/blob/main/langgraph/pregel/__init__.py#L558
1. Create new `_defaults()` method.
2. Create new `streamChannelsAsIs` getter. `_defaults()` depends on this.
3. Create new `All` (`*`) string literal type. `_defaults()` depends on this. However, this feature was added as part of another feature unrelated to `_defaults()`. See this PR: https://github.com/langchain-ai/langgraph/pull/367.
1. Update `Pregel` `invoke()` and `stream()` methods.
2. Update Graph APIs and remaining Pregel state APIs.
=> Implement new `Pregel._defaults()` method to match Python implementation

langgraph/src/graph/graph.ts, langgraph/src/graph/state.ts, langgraph/src/prebuilt/chat_agent_executor.ts, langgraph/src/pregel/index.ts, langgraph/src/pregel/io.ts, langgraph/src/pregel/read.ts, langgraph/src/tests/prebuilt.test.ts, langgraph/src/tests/pregel.test.ts
- enables more dynamic graphs in future
- implement stream_mode=updates
- fix extra options keys being passed to nodes
- fix stream_mode for invoke
- fix issue where writes array for each task wasn't used
=> Rewrite StateGraph.compile and and MessageGraph.compile to delegate to new CompiledStateGraph methods

langgraph/src/graph/message.ts, langgraph/src/graph/state.ts, langgraph/src/prebuilt/index.ts, langgraph/src/prebuilt/tool_node.ts, langgraph/src/pregel/read.ts, langgraph/src/utils.ts
=> Implement prebuilt ToolNode, toolCondition, MessagesState

langgraph/src/pregel/index.ts
=> Add checkpoint for input values

langgraph/package.json, langgraph/src/channels/base.ts, langgraph/src/checkpoint/base.ts, langgraph/src/checkpoint/id.ts, langgraph/src/checkpoint/memory.ts, langgraph/src/checkpoint/sqlite.ts, langgraph/src/pregel/index.ts, langgraph/src/tests/checkpoints.test.ts, langgraph/src/tests/pregel.test.ts, langgraph/src/tests/utils.ts, yarn.lock
=> Use uuid6 for checkpoint id

langgraph/src/channels/dynamic_barrier_value.ts, langgraph/src/channels/named_barrier_value.ts, langgraph/src/channels/topic.ts, langgraph/src/graph/graph.ts, langgraph/src/graph/state.ts, langgraph/src/prebuilt/agent_executor.ts, langgraph/src/prebuilt/chat_agent_executor.ts, langgraph/src/pregel/index.ts, langgraph/src/tests/chatbot.int.test.ts, langgraph/src/tests/pregel.test.ts
- fix serialization of named barrier value
- fix serialization of topic channel
=> Add conditional edge "then" arg

langgraph/src/checkpoint/base.ts, langgraph/src/checkpoint/memory.ts, langgraph/src/checkpoint/sqlite.ts, langgraph/src/pregel/index.ts, langgraph/src/pregel/types.ts
=> Implement getState, updateState, getStateHistory

langgraph/src/prebuilt/react_agent_executor.ts, langgraph/src/tests/prebuilt.int.test.ts, langgraph/src/tests/prebuilt.test.ts
Also use named params or whatever instead of positional ones in `createReactAgent`
=> Accept Async Messages Modifier

langgraph/src/checkpoint/base.ts, langgraph/src/graph/graph.ts, langgraph/src/graph/state.ts, langgraph/src/pregel/index.ts, langgraph/src/pregel/io.ts, langgraph/src/tests/checkpoints.test.ts, langgraph/src/tests/pregel.test.ts
=> Remove then= arg in cond edge

langgraph/package.json, langgraph/src/graph/graph.ts, langgraph/src/graph/state.ts, langgraph/src/pregel/index.ts, package.json, yarn.lock
Needed to remove the `const` in generic types, as it's only available in TS 5. Not sure exactly what the consequences of removing this feature are but code changes seemed small?
Sets `resolutions` to `typescript@4.9.5` to test, might not be a bad thing going forwards to resolve to the minimum allowable version.
CC @nfcampos @andrewnguonly
=> Add support for TS 4.9.5

langgraph/src/tests/tracing.test.ts, langgraph/src/utils.ts
Long term should try to work this into core but short-term fix for now:
@nfcampos
=> Properly pass config from async local storage into conditional edges

langgraph/src/checkpoint/index.ts, langgraph/src/web.ts
This PR exports `CheckpointTuple` and `SerializerProtocol` interfaces to allow checkpointer contributions from 3rd party pkgs. @jacoblee93
=> fix: export checkpointer interfaces

examples/multi_agent/agent_supervisor.ipynb
The purpose of this small PR is to fix a broken link (i.e. the one titled "The previous example") in the `agent_supervisor.ipynb` example docs.
**BEFORE** (clicking the link takes to `404`):
**AFTER** (clicking the link takes to the actual page):
=> Fix: broken link in agent_supervisor.ipynb

docs/docs/concepts/index.md, langgraph/src/channels/binop.ts, langgraph/src/graph/state.ts, langgraph/src/tests/graph.test.ts
Types are tricky and could use a refactor in general, but this unblocks an immediate issue
Supports
```
def update_dialog_stack(left: list[str], right: Optional[str]) -> list[str]:
"""Push or pop the state."""
if right is None:
return left
if right == "pop":
return left[:-1]
return left + [right]
```
CC @nfcampos @hinthornw @andrewnguonly
=> Loosen types to allow reducers with different update types

langgraph/package.json, yarn.lock
I released an actual release of `@langchain/scripts` on v`0.0.19` so no need to use the rc anymore.
=> infra[patch]: Use non rc of langchain/scripts 0.0.19

langgraph/package.json, langgraph/src/channels/base.ts, langgraph/src/graph/message.ts, langgraph/src/graph/state.ts, langgraph/src/tests/graph.test.ts, package.json, yarn.lock
This more closely matches python, where a single declaration gives you all three
=> Define StateGraph State in a single delcaration, from which both reducers and state and update interfaces are inferred

langgraph/src/pregel/index.ts, package.json, yarn.lock
=> Use config.signal to control cancellation

.github/workflows/validate-new-notebooks.yml, package.json, scripts/validate_deps_sync.ts, yarn.lock
The validate new notebook gh action requires the notebook dependencies to be installed w/ npm, but notebooks do not require deps to be listed in a package.json (`deno.json`)
This script & gh action verifies that all dependencies listed in the `deno.json` file are also present in the `examples/package.json` file, and the version is greater than or equal to that in `deno.json`
=> ci[minor]: Add script & GH action to validate deno and node deps in sync

langgraph/src/pregel/algo.ts, langgraph/src/tests/pregel.test.ts
=> fix(algo): only return channels which actually triggered the task

libs/checkpoint/src/memory.ts, libs/checkpoint/src/serde/jsonplus.ts, libs/checkpoint/src/serde/tests/jsonplus.test.ts, libs/langgraph/src/pregel/index.ts, libs/langgraph/src/pregel/loop.ts, libs/langgraph/src/pregel/types.ts, libs/langgraph/src/tests/pregel.test.ts
Cleans up instances where we do it internally, can also occur if a user passes an `undefined` value into a node update step.
=> Handle explicit undefined values passed into serde

libs/langgraph/src/prebuilt/chat_agent_executor.ts, libs/langgraph/src/prebuilt/react_agent_executor.ts, libs/langgraph/src/tests/prebuilt.test.ts
=> fix(prebuilt): use messagesStateReducer to support more formats

.github/workflows/validate-new-notebooks.yml, examples/quickstart.ipynb, libs/langgraph/src/prebuilt/tool_node.ts, libs/langgraph/src/tests/prebuilt.test.ts
Right now you have to manually pass a type in pretty much all cases, which isn't nice.
@bracesproul
=> langgraph[patch]: Relax tool node generic requirement

libs/langgraph/src/pregel/index.ts, libs/langgraph/src/pregel/loop.ts, libs/langgraph/src/tests/pregel.test.ts
If checkpointing is slow, it is possible for an error to be thrown outside of the loop.
=> fix: Fix async checkpoint error handling

libs/checkpoint/src/memory.ts, libs/checkpoint/src/serde/jsonplus.ts, libs/checkpoint/src/serde/types.ts, libs/langgraph/src/graph/graph.ts, libs/langgraph/src/pregel/index.ts
Will probably want to do the same for the other implementations
=> fix(checkpointers): Avoid storing Sends twice in memory checkpointer

docs/overrides/main.html
=> docs[minor]: Add state of agents survey to docs announcement bar

examples/quickstart.ipynb
Adds a missing dependency needed to run the quickstart
=> docs: Add @langchain/core to quickstart

examples/how-tos/persistence.ipynb
=> Update ToolNode link to correct documentation link

README.md, libs/langgraph/README.md
StateGraphArgs is not used in the code
And it anyway throws an error: 
```
import { StateGraph, StateGraphArgs } from "@langchain/langgraph";
^^^^^^^^^^^^^^
SyntaxError: The requested module '@langchain/langgraph' does not provide an export named 'StateGraphArgs'
```
=> Remove StateGraphArgs

libs/checkpoint/src/memory.ts
Found while working on #541.
Prior to this fix, when `MemorySaver.getTuple` was called to fetch a specific `checkpoint_id` that was a child of some other checkpoint, the value of `parentConfig.configurable.checkpoint_id` in the returned `CheckpointTuple` would be assigned to the child's `checkpoint_id` rather than the parent's.
=> fix: return correct checkpointId in parentConfig in MemorySaver.getTuple

libs/langgraph/src/errors.ts, libs/langgraph/src/graph/graph.ts, libs/langgraph/src/graph/state.ts, libs/langgraph/src/pregel/index.ts, libs/langgraph/src/pregel/io.ts, libs/langgraph/src/pregel/loop.ts, libs/langgraph/src/pregel/retry.ts, libs/langgraph/src/pregel/types.ts, libs/langgraph/src/tests/pregel.io.test.ts, libs/langgraph/src/tests/pregel.test.ts
=> feat(langgraph): Allow option to prevent subgraphs inheriting checkpointer

libs/checkpoint/src/memory.ts
Per the title, adds support for the `options.filter` argument to `MemorySaver`.list (another one from #541).
I suppose this could be a `feat` instead of a `fix`, but I opted to call it the latter as it's a part of the core checkpoint interface that was never implemented in `MemorySaver`.
=> fix(checkpoint): add support for options.filter in MemorySaver.list

libs/checkpoint/src/memory.ts
Prior to this change, if you passed a `thread_id` to `MemorySaver.list` that wasn't stored, the changed line would throw due to `this.storage[threadId]` evaluating to `undefined`.
Found while working on #541.
=> fix(checkpoint): don't throw in MemorySaver.list if thread not found

libs/checkpoint-postgres/src/index.ts
Found while working on #541. Prior to this change, if you called the `list` method in `PostgresSaver` with an empty `configurable` object (e.g. `saver.list({ configurable: {} })`), you'd get back no results. This was due to a small error in the branching logic for building up the `WHERE` clause that is used to query for checkpoints.
Also, like in #576, I noticed that the `LIMIT` clause was being directly concatenated into the query without sanitization (a potential SQL injection vulnerability), so I went ahead and fixed that in this commit as well.
=> fix(checkpoint-postgres): fix WHERE clause generation on list

libs/checkpoint-sqlite/src/index.ts, libs/checkpoint-sqlite/src/tests/checkpoints.test.ts
This PR fixes a few issues in the `list` method of `SqliteSaver` that were found while working on #541.
- Fixes a SQL syntax error resulting from an empty `WHERE` clause when none of the filtering options are specified
- Adds missing support for filtering on `config.configurable.checkpoint_ns`
- Sanitizes `limit` field prior to concatenating
- Adds support for the `filter` field in the `options` argument by parsing the stored metadata in a CTE
Submitting these together because they're all somewhat intertwined.
=> fix(checkpoint-sqlite): list method bug fixes

libs/checkpoint-validation/bin/cli.js, libs/checkpoint-validation/src/cli.ts, libs/checkpoint-validation/src/runtime_jest_config.ts, libs/checkpoint-validation/tsconfig.cjs.json, libs/checkpoint-validation/tsconfig.json
Unfortunately the initial release of `@langchain/langgraph-checkpoint-validator` is broken for two reasons.
1. A bug in `@swc-node/register` attempts to resolve SWC packages from the CWD rather than the installed package's `node_modules` directory.
2. The jest config used by the CLI wasn't included in the release because I forgot to add it to the `files` array in `package.json`.
I fixed the first issue by applying the workaround mentioned here: https://github.com/swc-project/swc-node/pull/805#issuecomment-2257146304.
I fixed the second issue by moving the runtime jest config into the `src` dir and making it a TS file.
I tested this locally using `npm link` and it seems to fix both issues.
Sorry for the hiccup!
=> fix(checkpoint-validation): fix broken initial release

libs/langgraph/src/graph/graph.ts, libs/langgraph/src/graph/state.ts, libs/langgraph/src/pregel/algo.ts, libs/langgraph/src/pregel/debug.ts, libs/langgraph/src/pregel/index.ts, libs/langgraph/src/pregel/read.ts, libs/langgraph/src/pregel/types.ts, libs/langgraph/src/pregel/utils/subgraph.ts, libs/langgraph/src/tests/pregel.test.ts
Unlike in Python, we need to specify the subgraphs beforehand when adding nodes with lambdas that invoke the subgraph. 
This is necessary to ensure that:
1. Nested interrupts are properly handled
2. Debug stream events include checkpoint metadata
3. Both the graph and the subgraph are introspectable
=> feat(langgraph): add subgraph add node option to explicitly specify subgraphs

libs/checkpoint-validation/src/spec/put.ts, libs/checkpoint/src/memory.ts
For consistency with the other checkpointers, this change makes `MemorySaver.put` use the default namespace when `config.configurable.checkpoint_ns` is undefined.
Also unignores relevant tests in `checkpoint-validation` for `MemorySaver` runs.
Fixes #591
=> fix(checkpoint): don't throw on MemorySaver.put if no checkpoint_ns

libs/checkpoint-sqlite/src/index.ts, libs/checkpoint-validation/src/spec/list.ts
Per the title, fixes up `put` and `getTuple` on `SqliteSaver` to correctly populate the `pending_sends` and `pendingWrites` fields. Also adds a couple of input validation checks.
Finally, this change also modifies `checkpoint-validation` accordingly to unignore tests for `SqliteSaver`.
Fixes #590.
=> fix(checkpoint-sqlite): populate pending_sends and pendingWrites

libs/checkpoint-validation/.eslintrc.cjs, libs/checkpoint-validation/src/tests/mongodb_initializer.ts, libs/checkpoint-validation/src/tests/postgres_initializer.ts, libs/checkpoint-validation/src/tests/sqlite.spec.ts, libs/checkpoint-validation/src/tests/sqlite_initializer.ts
No idea why ESLint falsely triggered on the `zod` import in `checkpoint-validation`, but this appears to fix it.
[CI run of this commit on my fork](https://github.com/benjamincburns/langgraphjs/actions/runs/11513705853) is ✅ .
=> chore(checkpoint-validation): fix eslint extraneous-import error

libs/langgraph/.gitignore, libs/langgraph/langchain.config.js, libs/langgraph/package.json, libs/langgraph/src/errors.ts, libs/langgraph/src/graph/graph.ts, libs/langgraph/src/pregel/index.ts, libs/langgraph/src/pregel/remote.ts, libs/langgraph/src/pregel/types.ts, libs/langgraph/src/pregel/utils/subgraph.ts, libs/langgraph/src/remote.ts, libs/langgraph/src/tests/remote.int.test.ts, libs/langgraph/src/tests/remote.test.ts, libs/langgraph/src/web.ts, yarn.lock
Tests to follow - `getGraph()` and `getSubgraphs()` are unfortunately sync right now, so made new, bespoke async methods for now.
SDK typing also seems to be off in a few cases, will dig in further once tests are finished.
=> feat(langgraph): Adds RemoteGraph

examples/chatbots/customer_support_small_model.ipynb
Fixes type: `becuase` => `because`
=> docs: Fix typo

examples/rag/langgraph_crag.ipynb
While following the LangGraph tutorial, I encountered an issue where the tutorial was missing the @langchain/langgraph dependency. After adding this dependency, the errors were resolved. This PR updates the tutorial documentation to include the missing dependency installation step to help prevent others from encountering the same issue.
My username on X.com is @greyson_codes
=> fix(docs): added missing dependency in tutorial by adding @langchain/langgraph

README.md, libs/langgraph/README.md
=> fix(docs): use `messagesStateReducer` instead of `concat` to match Python

libs/langgraph/src/tests/pregel.test.ts
Turns out it's already possible!
```typescript
const graph = new StateGraph(MessagesAnnotation)
.addNode("one", (state) => {
if (!state.messages.length) {
throw new Error("State not found");
}
return {
messages: [
...state.messages,
{
role: "user",
content: "success",
},
],
};
})
.addNode("two", () => {
throw new Error("Should not be called");
})
.addEdge(START, "one")
.addEdge("one", "two")
.addEdge("two", END)
.compile();
const result = await graph.nodes.one.invoke({
messages: [new HumanMessage("start")],
});
expect(result.messages).toBeDefined();
expect(result.messages).toHaveLength(2);
```
=> fix(langgraph): Add test for invoking a single node

libs/langgraph/src/pregel/debug.ts
=> fix(debug): interrupts task result double tuple format

libs/langgraph/src/constants.ts, libs/langgraph/src/interrupt.ts, libs/langgraph/src/pregel/messages.ts, libs/langgraph/src/tests/pregel.test.ts
=> fix(interrupt): match signature of GraphInterrupt created in interrupt()

libs/langgraph/src/graph/graph.ts, libs/langgraph/src/graph/state.ts, libs/langgraph/src/prebuilt/react_agent_executor.ts, libs/langgraph/src/pregel/index.ts, libs/langgraph/src/tests/graph.test.ts, libs/langgraph/src/tests/prebuilt.int.test.ts, libs/langgraph/src/tests/pregel.test.ts, libs/langgraph/src/tests/tracing.int.test.ts
Opting to fix output types in a different PR due to the complexity of `streamMode` 
Closes #628
=> feat(graph): passthrough input types to invoke/stream

libs/langgraph/src/errors.ts
This changes `NodeInterrupt`'s `message` to allow `any` type, rather than just a string.  This allows steps and tools to bubble up structured objects as interrupts, where they can be handled by the application.
My specific use case is the ability to make an API call and receive a 401 Unauthorized response that contains challenge parameters (such as `scope` or `max_age`) that indicate what authorization context is needed.  The step/tool throws a structured `NodeInterrupt` including the parameters from the challenge.   Then application then uses these parameters to bring the human in the loop with an OAuth 2.0 authorization request.
I discussed this with @jacoblee93 on an internal Slack channel.
Twitter: [@jaredhanson](https://x.com/jaredhanson)
=> Allow value of NodeInterrupt to be any (JSON-serializable) type.

libs/langgraph/src/prebuilt/tool_node.ts
This changes `ToolNode` to always re-throw `NodeInterrupt` errors, rather than feeding errors back into the agent.
As documented [here](https://langchain-ai.github.io/langgraphjs/how-tos/dynamic_breakpoints/), the intent of `NodeInterrupt` is to act as a breakpoint for when a human needs to be brought into the loop.  This works as intended when thrown from a step function.  However, when wrapped in a `ToolNode`, the default behavior traps `NodeInterrupt` and feeds it back to the agent.   This is unexpected, since if a human is necessary the agent can't recover on its own.
Furthermore, setting `handleToolErrors` to `false` is a way to workaround this, but that then requires the developer to feed all other non-NodeInterrupt errors back manually (which is also unexpected).
The best default …
=> fix(langgraph): Re-throw NodeInterrupt errors from ToolNode for HITL.

docs/docs/how-tos/index.md
Closing #744 because of dep install commit that shouldnt be there
=> fix(docs): Update how to index HITL

libs/langgraph/src/tests/errors.test.ts
Test logic taken directly from #779. That issue fails to reproduce in this version, but it seemed like a good idea to add it to the suite.
=> chore(langgraph): test errors thrown from conditional edges

libs/langgraph/src/errors.ts, libs/langgraph/src/pregel/index.ts, libs/langgraph/src/pregel/loop.ts, libs/langgraph/src/pregel/retry.ts, libs/langgraph/src/pregel/runner.ts
This work is a prerequisite to porting the imperative (functional?) API over from python LangGraph.
=> patch(langgraph): Refactor pregel loop to use new `PregelRunner` class, ported from python LangGraph.

libs/langgraph/src/pregel/index.ts, libs/langgraph/src/tests/pregel.test.ts
Passes through signal to `PregelRunner` and adds test to guard against this regression in the future.
=> fix(langgraph): abort graph execution when config.signal is aborted

libs/langgraph/src/pregel/retry.ts, libs/langgraph/src/pregel/runner.ts, libs/langgraph/src/pregel/utils/config.ts, libs/langgraph/src/tests/pregel.test.ts
This is a follow-up to #795. The change in #795 caused the stream to abort, but not the pregel loop execution.
This change 
- prevents the `AbortSignal` from being filtered out of the config object that's handed off to the `PregelRunner`
- ensures that the abort error type is consistent
- checks the abort signal in the retry loop so we don't retry tasks after abort
=> fix(langgraph): make sure the pregel loop aborts on cancellation

CONTRIBUTING.md, docs/docs/concepts/double_texting.md, docs/docs/tutorials/workflows/index.md, libs/checkpoint-mongodb/README.md, libs/checkpoint-postgres/README.md, libs/checkpoint-postgres/src/index.ts, libs/checkpoint-sqlite/README.md, libs/checkpoint/README.md, libs/langgraph/src/tests/channels.test.ts, libs/langgraph/src/tests/func.test.ts, libs/langgraph/src/tests/pregel.read.test.ts, libs/langgraph/src/tests/pregel.test.ts
I noticed a handful of typos/invalid JSON properties while reading through the documentation and code for some of the checkpointer integrations. 
Thought I'd submit a quick PR to fix them up.
Thanks!
=> fix(docs/etc): Fix miscellaneous typos

README.md, libs/langgraph/README.md
=> fix(docs): adjust list appearance in README

examples/rag/langgraph_crag.ipynb
Fix CRAG tutorial tool invocation issue
Resolved an issue where the tool invocation in the CRAG tutorial was not working.
Origin: query
Fixed: input
=> fix(docs): crag wrong tool invocation

docs/overrides/main.html
=> Interrupt banner

libs/langgraph/src/graph/message.ts, libs/langgraph/src/tests/prebuilt.test.ts
There are some cases where duplicate messages (with the same id) can accumulate in a result in before they are returned by a node and passed into a reducer
This change dedupes in new messages
FYI @benjamincburns @nfcampos
=> fix(langgraph): Dedupe input (right-side) messages in messageStateReducer

libs/langgraph/src/pregel/remote.ts
~Marking as draft, because we might want to deserialise raw JSON objects to actual messages~ Turns out the Python's RemoteGraph does not convert the message tuples back to BaseMessage anyway
https://github.com/langchain-ai/langgraphjs/issues/684
=> fix(remote): use "messages-tuple" when requesting "messages"

libs/langgraph/src/pregel/messages.ts, libs/langgraph/src/tests/pregel.test.ts, libs/langgraph/src/tests/utils.ts
=> fix(messages): reuse the first valid message ID for subsequent chunks

libs/checkpoint-postgres/README.md, libs/checkpoint-postgres/src/index.ts, libs/checkpoint-postgres/src/migrations.ts, libs/checkpoint-postgres/src/sql.ts, libs/checkpoint-postgres/src/tests/checkpoints.int.test.ts
This PR adds support for specifying a custom schema in the `checkpoint-postgres` module during initialization. Instead of relying on the default `public` schema used by Postgres or modifying the connection string’s search path (which can be unreliable at best), SQL queries now explicitly reference the provided schema, ensuring compatibility across all PostgreSQL versions and configurations, while still allowing the original module to stay backward compatible with previous versions since `public` was already the default schema.
```ts
// you can optionally pass a configuration object as the second parameter
const checkpointer = PostgresSaver.fromConnString("postgresql://...", {
schema: "schema_name" // defaults to "public"
});
```
- **Custom Schema Support**
- Added an extendable `options` …
=> feat(checkpoint-postgres): Add support for providing a custom schema during initialization

libs/checkpoint-mongodb/src/index.ts
Issue
The MongoDB checkpoint storage implementation currently does not properly handle UTF-8 encoded input (such as Chinese characters). When retrieving checkpoints via getTuple, message contents containing non-ASCII characters are corrupted and displayed as garbled text.
Changes
Added proper UTF-8 encoding support for MongoDB checkpoint storage
Ensures correct storage and retrieval of non-ASCII characters in checkpoint messages
Maintains data integrity for international character sets
Impact
This fix enables LangGraphJS to properly handle international text in conversations and workflows when using MongoDB as the checkpoint storage backend. Users working with non-English languages will now see their content preserved correctly throughout the graph execution process.
=> fix(checkpoint-mongodb): fix utf8 encoding support

libs/langgraph/tsconfig.json, package.json, yarn.lock
Reverts:
- a change to langgraph `tsconfig.json` that broke CJS support
- an unnecessary upgrade of `typedoc` that causes it to depend on latest `typescript` and appears to break docs builds
=> fix(langgraph,docs): revert previous changes that broke builds

docs/docs/concepts/streaming.md
Example was calling `streamEvents` without the required 2nd arg.
=> fix(docs): fix broken example in streaming concepts doc

libs/langgraph/package.json, libs/langgraph/src/pregel/messages.ts, libs/langgraph/src/tests/pregel.test.ts
Tool messages usually don't have a message ID, thus assigning a message ID inferred from run ID will cause parallel tool responses to be dropped, as they will be merged.
=> fix(messages): avoid assigning same ID for tool messages

docs/overrides/partials/integrations/analytics.html, docs/overrides/partials/integrations/analytics/google.html
Communicates cookie consent preferences back to Google and uses cookieless mode when users decline cookies.
=> chore(docs): proper use of GA consent mode

libs/langgraph/src/prebuilt/react_agent_executor.ts, libs/langgraph/src/tests/prebuilt.test.ts, libs/langgraph/src/tests/utils.ts
Fixes #921 
Support bedrock tool spec with createReactAgent with bound tools
=> fix(langgraph): support bedrock tool spec with createReactAgent with bound tools

libs/langgraph-swarm/README.md
Now that `langgraph-swarm` has been ported to LangGraphJS, I thought I'd take a quick look at it and noticed a minor typo likely due to a find and replace missing it due to the casing.
Thought I'd fix it up real quick.
Thanks!
=> fix(docs): Replace "Python" with "JavaScript" in swarm README

libs/langgraph/src/tests/pregel.test.ts, libs/langgraph/src/tests/pregel/pregel.cancellation.test.ts
Also validates that
- The signal received by nodes
- fires in the event of a timeout
- fires in the event of an external trigger (user code calling `abort` on the associated `AbortController`)
- propagates correctly from parent graphs into subgraphs
- when subgraph is called from within a node w/o explicitly passing `config`
- when subgraph is a node
=> chore(langgraph): add tests to validate AbortSignal is passed into nodes

libs/checkpoint-mongodb/package.json, libs/checkpoint-sqlite/package.json, libs/checkpoint-validation/package.json, yarn.lock
Fixes gyp compilation errors on Node.js >= 23.4.0 (LTS):
```
prebuild-install warn install No prebuilt binaries found (target=23.7.0 runtime=node arch=arm64 libc= platform=darwin)
gyp info it worked if it ends with ok
gyp info using node-gyp@11.1.0
gyp info using node@23.7.0 | darwin | arm64
gyp info find Python using Python version 3.13.2 found at "/opt/homebrew/opt/python@3.13/bin/python3.13"
gyp info spawn /opt/homebrew/opt/python@3.13/bin/python3.13
gyp info spawn args [
gyp info spawn args '/Users/divy/gh/langgraphjs/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args 'binding.gyp',
gyp info spawn args '-f',
gyp info spawn args 'make',
gyp info spawn args '-I',
gyp info spawn args '/Users/divy/gh/langgraphjs/node_modules/better-sqlite3/build/config.gypi',
gyp info spawn args …
```
=> fix(checkpoint-sqlite): upgrade better-sqlite3 to 11.7.0

examples/how-tos/time-travel.ipynb
Minor change, fixed a dead link I've found while reading the docs.
=> Updated dead link in time-travel docs

libs/langgraph/src/pregel/index.ts, libs/langgraph/src/tests/pregel.test.ts
This method is useful for recreating a thread from a list of checkpoint writes. A new method is needed to clone a checkpoint that has been created from multiple writes (functional API, map-reduce)
=> feat(pregel): add bulk update state method

libs/langgraph/src/constants.ts, libs/langgraph/src/pregel/index.ts, libs/langgraph/src/tests/pregel.test.ts
- Add option to submit an update as input, creates a `source: input` checkpoint that will contain `__start__` task, which can be populated with a second update
- Also adds a test for expected usage + map reduce patterns
=> feat(pregel): add ability to bulk update as input

docs/docs/llms-txt-overview.md, docs/mkdocs.yml
Add an overview page for users that tells them where to find llms.txt and llms-full.txt and how those files could be used.
=> feat(docs): add llms-overview file

libs/langgraph/src/graph/graph.ts
Fixes type checks when adding edges on `Graph`
=> fix(langgraph): allow setting edges from START on Graph

examples/how-tos/breakpoints.ipynb, examples/quickstart.ipynb
Inspired by the below conversation in the LangChain Community Slack, I have added an example to the Quickstart documentation page for how to save the mermaid representation of the graph to a local PNG file.
I also noticed a minor typo in the how-to breakpoints doc which I fixed while I was in the area.
Thanks!
=> fix(docs): Add section to demonstrate saving a graph diagram locally

libs/langgraph-swarm/src/swarm.ts, libs/langgraph/package.json, libs/langgraph/src/graph/state.ts, libs/langgraph/src/graph/zod.ts, libs/langgraph/src/graph/zod/schema.ts, libs/langgraph/src/graph/zod/state.ts, libs/langgraph/src/tests/pregel.test.ts, yarn.lock
This PR adds an alternative method of defining schema of an agent, with the primary goal having the ability to extract the schema of the graph in runtime, rather than relying on `tsc`
Follow-up PRs:
- https://github.com/langchain-ai/langgraphjs/pull/1024
- https://github.com/langchain-ai/langgraphjs/pull/1025
- https://github.com/langchain-ai/langgraphjs/pull/1029
=> feat(langgraph): add Zod support for state definition / config schema

libs/langgraph/src/graph/state.ts, libs/langgraph/src/graph/zod/schema.ts, libs/langgraph/src/graph/zod/state.ts, libs/langgraph/src/pregel/index.ts, libs/langgraph/src/tests/pregel.test.ts
Rely on parsing and post-processing description, similar to how `jsonDescription` works in `zod-to-json-schema`. Avoiding use of `postprocess` for now: https://github.com/StefanTerdell/zod-to-json-schema?tab=readme-ov-file#using-postprocess-for-including-examples-and-other-meta
Related PRs
- https://github.com/langchain-ai/langgraphjs/pull/1029
=> feat(pregel): add Zod config schema + langgraph studio meta properties

libs/langgraph-cua/package.json, yarn.lock
`@langchain/openai` `0.5.1` fixed a bug with sending requests to OpenAI's responses API when the chat history is managed by the user, and `previous_response_id` is not used. Specifically for sending the `reasoning` output blocks back to the API.
=> fix(cua): Bump min version for OpenAI peer dep

libs/langgraph/.eslintrc.cjs, libs/langgraph/src/constants.ts, libs/langgraph/src/pregel/index.ts, libs/langgraph/src/pregel/retry.ts, libs/langgraph/src/pregel/runner.ts, libs/langgraph/src/pregel/stream.ts, libs/langgraph/src/pregel/types.ts, libs/langgraph/src/pregel/utils/index.ts, libs/langgraph/src/tests/pregel/pregel.cancellation.test.ts, libs/langgraph/src/tests/python_port/graph_structure.test.ts, libs/langgraph/src/tests/python_port/interrupt.test.ts
The `AbortSignal` passed to each node via the `signal` field on the node's `config` argument now aborts when:
- The `AbortSignal` passed into `Pregel.invoke`, `Pregel.stream`, or `Pregel.streamEvents` via `config.signal` is aborted.
- The currently executing graph super-step times out.
- Any other node executing concurrently within the same superstep throws an `Error`.
- Note: "bubble-up" errors (e.g. `NodeInterrupt` and `CommandParent`) will _not_ trigger an abort.
- The `cancel` method is called on the stream returned by `Pregel.stream` or `Pregel.streamEvents`.
Importantly, `AbortSignal` are also now composed intelligently throughout the graph execution, allowing for a node in a parent graph to call a subgraph with an `AbortSignal` that originates in the node, and the signal received …
=> fix(langgraph): compose & propagate AbortSignal correctly, trigger on more early termination cases

libs/langgraph/src/tests/pregel/pregel.cancellation.test.ts
Adds tests that validate that invoking a thread after an abort starts the thread from the last successful state.
=> chore(langgraph): add tests to verify initial state for invocations after abort

README.md, libs/langgraph/README.md
Proposing adding the `create-agent-chat-app` command under a `Quickstart` section to the LangGraph docs.
=> feat(docs): Add create-agent-chat-app to readme quickstart

libs/langgraph/src/pregel/loop.ts, libs/langgraph/src/tests/pregel.test.ts
1. `Command(goto=...)` needs to be treated separately from `Command(update=...)` and `Command(goto=....)` w.r.t. writes and checkpoints. If a checkpoint is not created, the pending write will get lost if the `Command(goto=...)` enters into a node that interrupts
2. We actually did create a new checkpoint pre-#1023 (`isResuming=false`), but because we mapped and wrote the input twice, it also scheduled the start node. Thus, adding a new branch for non-resume Command seems reasonable to me.
=> fix(langgraph): goto + interrupt handling

docs/docs/tutorials/workflows/index.md
This pull request includes a minor formatting change to the `docs/docs/tutorials/workflows/index.md` file. The change ensures that all method calls in the `parallelWorkflow` construction are consistently terminated with a semicolon.
Formatting consistency:
* [`docs/docs/tutorials/workflows/index.md`](diffhunk://#diff-454e58a05b59d326cf3708060a8af550546fe322022576b3b434f89a89adba9eL299-R309): Updated the `parallelWorkflow` construction to ensure all method calls are consistently terminated with a semicolon.
=> fix(docs): improve code formatting in workflows tutorial

libs/langgraph/src/pregel/loop.ts, libs/langgraph/src/tests/pregel.test.ts
Closes Command resume with update throws, but docs show that it shouldn't. #1109
=> fix(langgraph): allow resume + update at the same time

libs/checkpoint-postgres/.gitignore, libs/checkpoint-postgres/src/index.ts, libs/checkpoint-postgres/src/sql.ts, libs/checkpoint-postgres/src/tests/checkpoints.int.test.ts, libs/checkpoint-postgres/tsconfig.json
Ensure that table `checkpoint_migrations` is created before the `SELECT` query.
This will prevent the error of non-existing table
Also fixed some minor code style errors
Fixes #903
=> improve migration for PostgresSaver and error handling

yarn.lock
Pinning `rollup@npm:^4.5.2` to `4.40.1` and `tar-fs@npm:~2.0.1` to `2.1.2`
`tar-fs@~2.0.1` is used by dockerode, so feels safe to pin
=> fix(security): update tar-fs and rollup

libs/langgraph/src/graph/state.ts, libs/langgraph/src/tests/pregel.test.ts
Previously, the zod schema would be applied to the input even if it were a `Command`.
Skip that to avoid dropping resume/goto/etc.
=> Fix Command(resume) for Zod Schemas

libs/langgraph/src/graph/state.ts, libs/langgraph/src/tests/graph.test.ts, libs/langgraph/src/tests/pregel.test.ts
Port of https://github.com/langchain-ai/langgraph/pull/2352, allows both `[key: string, action: function][]` and `{ [key: string]: function }`
Objects might be a little bit strange, but I think in current JS engine implementation of `Object.entries` is reasonably defined for us to do this.
>  Within each component of the prototype chain, all non-negative integer keys (those that can be array indices) will be traversed first in ascending order by value, then other string keys in ascending chronological order of property creation.
=> feat(langgraph): add addSequence method

libs/langgraph/src/graph/message.test.ts, libs/langgraph/src/graph/message.ts, libs/langgraph/src/pregel/messages.ts
This method is especially useful when yielding a manual AI message to bind Gen UI elements and for allowing other libraries to use `messages` / `messages-tuple` stream
=> feat(langgraph): add pushMessage method

libs/langgraph/src/pregel/utils/index.ts
Replacing to our polyfill does seem to avoid spurious memory leaks on v22.14. See https://github.com/nodejs/node/issues/55328 for more details
=> fix(langgraph): memory leak when using AbortSignal.any(...)

libs/langgraph/src/graph/state.ts
=> fix(langgraph): improve error message when attempting to pass an invalid argument to `StateGraph`

libs/langgraph/src/constants.ts, libs/langgraph/src/pregel/index.ts, libs/langgraph/src/pregel/loop.ts, libs/langgraph/src/pregel/types.ts, libs/langgraph/src/tests/func.test.ts, libs/langgraph/src/tests/pregel.test-d.ts, libs/langgraph/src/tests/pregel.test.ts, libs/langgraph/src/tests/python_port/checkpoint.test.ts, libs/langgraph/src/tests/python_port/graph_structure.test.ts, libs/langgraph/src/tests/python_port/interrupt.test.ts, libs/langgraph/src/web.ts
Partial port of https://github.com/langchain-ai/langgraph/pull/4374, does not tackle multi-resumes for now
=> feat(langgraph): return interrupts with `streamMode: "values"`

libs/langgraph-cua/package.json, yarn.lock
Relax `peerDependencies` constraint to support `@langchain/langgraph 0.3.x`
=> release(cua): 0.0.6

libs/langgraph-supervisor/package.json, yarn.lock
Relax `peerDependencies` constraint to support `@langchain/langgraph 0.3.x`
=> release(supervisor): 0.0.13

libs/checkpoint/package.json, libs/langgraph/package.json
Fixes an issue that blocks the release script from continuing after tests passed.
We changed the `test` scripts to enter into vitest watch mode by default, so in order to release you had to add `CI=true` to tell vitest that it shouldn't do that.
=> chore: use 'vitest run' to unblock release script

libs/langgraph/src/pregel/debug.test.ts, libs/langgraph/src/pregel/debug.ts, libs/langgraph/src/pregel/index.ts, libs/langgraph/src/pregel/loop.ts, libs/langgraph/src/pregel/types.ts, libs/langgraph/src/tests/pregel.test.ts
Prerequisite of removal of `metadata.writes`
=> feat(langgraph): populate task results

libs/langgraph/src/graph/zod/zod-registry.ts
`.registry(...)` does not support modifying the `input` Zod internal, thus the input types for graphs are incorrectly inferred to output type. Goal is to augment `ZodType` with an overloaded `.registry(LanggraphZodMetaRegistry)` method, that casts the return type to proper schema.
=> fix(langgraph): zod 4 registry reducer schema

libs/langgraph/src/pregel/validate.test.ts, libs/langgraph/src/pregel/validate.ts
**Description:**
```
This PR addresses a minor typo in an error message related to channel subscriptions.
- Corrected "Subcribed" to "Subscribed" in the validation error message.
- Updated the corresponding unit test to expect the corrected error message.
```
=> Fix: Correct typo in "Subscribed" error message

libs/langgraph/src/channels/base.ts, libs/langgraph/src/constants.ts, libs/langgraph/src/graph/state.ts, libs/langgraph/src/pregel/index.ts, libs/langgraph/src/pregel/loop.ts, libs/langgraph/src/pregel/types.ts, libs/langgraph/src/pregel/utils/config.ts, libs/langgraph/src/tests/pregel.test.ts, libs/langgraph/src/tests/utils.ts
Port of https://github.com/langchain-ai/langgraph/pull/4169
Closes Add `checkpoint_during` from LangGraph Python #1195
=> feat(langgraph): implement checkpoint_during

libs/langgraph-cua/package.json, libs/langgraph-supervisor/package.json, libs/langgraph-swarm/package.json, package.json, yarn.lock
`yarn build` will now call `build:internal`, avoiding nested calls to `turbo run`
=> chore(deps): bump turbo@2.5.4

libs/langgraph/src/pregel/debug.ts, libs/langgraph/src/pregel/loop.ts, libs/langgraph/src/pregel/types.ts, libs/langgraph/src/tests/pregel.test-d.ts, libs/langgraph/src/utils.ts
Split out the "debug" stream mode into more descriptive "tasks" and "checkpoints" stream mode, while removing the unnecessary wrapper object.
Port of https://github.com/langchain-ai/langgraph/pull/5117
=> feat(langgraph): add "tasks" and "checkpoints" stream mode

libs/langgraph/src/pregel/utils/config.ts
writer exists in runConfig.
fix getWriter to correctly pass writer.
=> fix(langgraph): change return value of getWriter

.changeset/afraid-ghosts-ask.md, libs/sdk/src/react/stream.tsx
`clear()` might be invoked before `setStreamValues` setter has been finished.
=> fix(sdk): useStream race condition when flushing messages

.changeset/olive-bottles-study.md, libs/langgraph/src/pregel/index.ts, libs/langgraph/src/pregel/runner.ts, libs/langgraph/src/pregel/types.ts, libs/langgraph/src/pregel/utils/index.ts, libs/langgraph/src/tests/pregel/pregel.cancellation.test.ts
- Avoids hidden chaining of combined abort signals with external signal, thus attaching a listener on each tick.
- Make sure to always remove the event listener on external abort signal when the combined signal is not used anymore
=> fix(langgraph): dispose unused combined signals

.changeset/wise-schools-boil.md, libs/langgraph/src/constants.ts, libs/langgraph/src/pregel/index.ts, libs/langgraph/src/tests/prebuilt.test.ts
Since TypeScript is a structural type system, it does not distinguish between an instance of Command and an object that has the same shape as a Command, thus `invoke(...) / stream(...)` suggests bogus keys.
We can (mis)use Symbols to still validate against an instance of Command while hiding these bogus keys.
=> fix(langgraph): stop suggesting public properties and methods of Command when calling invoke

.changeset/two-toes-chew.md, libs/checkpoint-mongodb/src/tests/checkpoints.int.test.ts, libs/checkpoint-postgres/src/tests/checkpoints.int.test.ts, libs/checkpoint-sqlite/src/index.ts, libs/checkpoint-sqlite/src/tests/checkpoints.test.ts, libs/checkpoint-validation/src/spec/delete_thread.ts, libs/checkpoint-validation/src/spec/get_tuple.ts, libs/checkpoint-validation/src/spec/list.ts, libs/checkpoint-validation/src/test_utils.ts, libs/checkpoint/src/tests/checkpoints.test.ts, libs/checkpoint/src/types.ts, libs/langgraph-api/tests/api.test.mts, libs/langgraph/src/pregel/index.ts, libs/langgraph/src/pregel/loop.ts, libs/langgraph/src/tests/pregel.test.ts, libs/langgraph/src/tests/python_port/checkpoint.test.ts, libs/langgraph/src/tests/python_port/graph_structure.test.ts, libs/langgraph/src/tests/python_port/interrupt.test.ts
Since we only need to restore from checkpoint values, we do not need to store the update values separately. Removing `writes` from metadata allows us to save space.
=> chore(checkpoint): remove checkpoint["writes"]

.changeset/tricky-rules-give.md, libs/checkpoint-mongodb/src/index.ts, libs/checkpoint-postgres/src/index.ts, libs/checkpoint-sqlite/src/index.ts, libs/checkpoint/src/memory.ts, libs/checkpoint/src/serde/base.ts, libs/checkpoint/src/serde/jsonplus.ts, libs/checkpoint/src/serde/tests/jsonplus.test.ts, libs/langgraph/src/tests/python_port/checkpoint.test.ts, libs/langgraph/src/tests/utils.ts
Deserialization was already async (which was hidden due to our usage of `any`). This implements async serialization as well.
Closes Allowing asynchronous serialization and deserialization within checkpoint savers #529
=> feat(checkpoint): allow async serialization / deserialization

.changeset/true-ties-sin.md, libs/sdk/src/react/stream.tsx
When `streamSubgraphs: true` is enabled, subgraph custom events (`custom|subgraph_id|node_id`) are not processed because the stream only checks for exact `event === "custom"` matches.
Updated event processing to handle both standard custom events and subgraph custom events by checking for events that start with "custom|".
- Modified event condition: `event === "custom" || event.startsWith("custom|")`
- Updated `EventStreamEvent` type to include subgraph variants
- Fixed null/undefined handling in stream processing functions
- TypeScript compilation passes
- Maintains backward compatibility
- Follows existing pattern for subgraph message events
This ensures UI components from subgraphs are properly rendered when streaming is enabled. Greetings from [Captide](https://www.captide.ai)!
=> fix: handle subgraph custom events in stream processing

.changeset/smooth-dragons-drive.md, libs/langgraph/src/prebuilt/tool_node.ts
Gracefully handle empty messages when deciding conditional mapping to "tools" or END
If messages is empty, message is assigned to `undefined`, and "tool_calls" in message will throw.
=> fix(langgraph): handle empty messages

.changeset/pretty-mice-boil.md, libs/langgraph-api/src/cli/spawn.mts, libs/langgraph-api/src/preload.mjs, libs/langgraph-api/src/server.mts, libs/langgraph-cli/src/docker/docker.mts, libs/langgraph-cli/src/utils/config.mts, libs/langgraph-cli/tests/config.test.mts
This PR allows for graph descriptions to exist within `langgraph.json`. When specified, LGP serves an `/mcp` endpoint which allows you to call your graphs like MCP tools. 
Note that we currently don't support MCP within the local dev server which we emit a warning for
=> fix(cli): allow description field on config

.changeset/fuzzy-vans-yell.md, .changeset/seven-lamps-matter.md, .changeset/slimy-singers-trade.md, libs/langgraph-cua/src/index.ts, libs/langgraph-cua/src/nodes/call-model.ts, libs/langgraph-cua/src/nodes/create-vm-instance.ts, libs/langgraph-cua/src/nodes/take-computer-action.ts, libs/langgraph-swarm/src/swarm.ts, libs/langgraph/src/graph/graph.ts, libs/langgraph/src/graph/state.ts, libs/langgraph/src/pregel/index.ts, libs/langgraph/src/pregel/types.ts, libs/langgraph/src/tests/errors.test.ts, libs/langgraph/src/tests/pregel.test-d.ts, libs/langgraph/src/tests/pregel.test.ts
Previously we were using the update types of state definition for `streamMode: updates`, which isn't useful in case of `Messages: string | BaseMessage | BaseMessageLike`.
=> feat(langgraph): use return types from nodes as update type

.changeset/cute-results-repair.md, libs/langgraph/src/pregel/algo.ts, libs/langgraph/src/pregel/utils/index.ts
- Avoid calling `channel.get()` when only checking for availability
- Avoid enumerating all channels just to obtain a null channel version
- Short-circuit to a well-known channel when obtaining channel version
Cuts down the `sequential_1000` benchmark from 32s down to 1.32s.
=> feat(langgraph): speed up prepareSingleTask by 20x

.changeset/green-roses-appear.md, libs/sdk-validation/src/tests/stream.test.tsx, libs/sdk/src/react/stream.tsx
Sometimes it is still useful to obtain message metadata sent as part of `messages-tuple` stream mode, even though these are only ephemeral in nature.
=> feat(sdk): expose stream metadata from messages via `getMessagesMetadata`

.changeset/olive-crabs-clap.md, libs/langgraph-supervisor/src/handoff.ts, libs/langgraph-supervisor/src/supervisor.ts, libs/langgraph-supervisor/src/tests/supervisor.test.ts, libs/langgraph/src/graph/state.ts, libs/langgraph/src/prebuilt/react_agent_executor.ts
Opted to specify `description` in `createReactAgent` instead of proposed solution in #1509, since we're already include the `name` property in `createReactAgent`, used for the handoff tool name.
Closes #1509
=> feat(langgraph): use createReactAgent description for supervisor agent handoffs

.changeset/cute-comics-refuse.md, libs/langgraph-api/src/graph/parser/parser.mts, libs/langgraph-api/src/graph/parser/schema/types.template.mts, libs/langgraph-api/tests/parser.test.mts
Use Equals type utility instead of Wrap
=> fix(api): unintended schema inference to BaseMessage[] for all state keys when `strictFunctionTypes: true`

.changeset/gorgeous-clocks-fail.md, libs/langgraph/src/pregel/utils/index.ts, libs/langgraph/src/tests/pregel/pregel.utils.test.ts
- Propagate `AbortSignal.reason` in `combineAbortSignals` so the combined signal carries through the originating abort reason.
- Add a unit test to validate reason propagation and combined abort behavior.
- Preserves cancellation context across combined signals (e.g., distinguish timeout vs. user-initiated cancels).
- Aligns with the WHATWG AbortController semantics where `abort(reason)` is surfaced to consumers.
- Improves debugging and error handling in Pregel flows that rely on abort reasons.
- Forward the `.reason` from the source signal that triggers the abort to the combined controller.
- Clean up listeners after abort to avoid leaks.
- New test `libs/langgraph/src/tests/pregel/pregel.utils.test.ts` covering combined signal behavior and reason propagation.
=> fix(pregel/utils): propagate abort reason in combineAbortSignals

.changeset/polite-areas-greet.md, libs/langgraph-api/src/http/middleware.mts
=> fix(api): prevent overriding default CORS config when applying a single override

.changeset/slick-eels-sneeze.md, libs/langgraph-supervisor/src/supervisor.ts
Implemented full support for preModelHook and postModelHook parameters in the createSupervisor function, bringing feature parity with the Python LangGraph implementation.
1. Added hook parameters to interface: Extended CreateSupervisorParams type to include preModelHook and postModelHook parameters with proper typing from CreateReactAgentParams
2. Implemented parameter passing: Updated the createSupervisor function to accept and pass through the hook parameters to the underlying createReactAgent call
3. Added comprehensive documentation: Enhanced JSDoc comments with detailed documentation for both hook parameters, including:
- Usage examples showing expected input/output format
- Important warnings about state management
- Best practices for message handling
- Adapted Python documentation …
=> feat (langgraph): Add preModelHook and postModelHook support to createSupervisor

libs/checkpoint-postgres/README.md
It's not clear in the NPM how we can reuse existing connection: https://www.npmjs.com/package/@langchain/langgraph-checkpoint-postgres
=> docs: add example to use existing conn pool

.changeset/red-ladybugs-fly.md, libs/langgraph-swarm/README.md, libs/langgraph/src/prebuilt/react_agent_executor.ts
We have renamed `createReactAgent` to `createAgent` in `langchain` and need to update the deprecation messages.
=> fix(createReactAgent): update deprecation messages to contain reactAgent

.changeset/bumpy-roses-lie.md, libs/langgraph-api/src/auth/custom.mts
=> fix(api): bypass custom auth middleware when requesting JS/CSS assets

.changeset/clean-planes-judge.md, libs/langgraph-api/src/api/assistants.mts, libs/langgraph-api/src/schemas.mts, libs/langgraph-api/src/storage/ops.mts, libs/langgraph-api/src/storage/types.mts, libs/langgraph-api/tests/api.test.mts, libs/sdk/src/auth/types.ts
This adds the optional `description` field to the `Assistant` model (for parity with the Python version).
=> chore(sdk, api): add description field for assistants

.changeset/clean-planes-judge.md, libs/langgraph-api/src/api/assistants.mts, libs/langgraph-api/src/schemas.mts, libs/langgraph-api/src/storage/ops.mts, libs/langgraph-api/src/storage/types.mts, libs/langgraph-api/tests/api.test.mts, libs/sdk/src/auth/types.ts
Reverts langchain-ai/langgraphjs#1640 (need to ship SDK changes first)
=> Revert "chore(sdk, api): add description field for assistants"

.changeset/good-pugs-reply.md, libs/langgraph/src/graph/index.ts
The `CommandInstance` symbol is currently not exported which causes the following TS error when using `Command` type anywhere:
```
The inferred type of 'clientConfigSchema' cannot be named without a reference to '.pnpm/@langchain+langgraph@1.0.0-alpha.1_@langchain+core@libs+langchain-core_react-dom@18.3.1_4b608615381ea52bef92f957a3a7853a/node_modules/@langchain/langgraph'. This is likely not portable. A type annotation is necessary.ts(2742)
```
=> fix(@langchain/langgraph): export missing symbol
