langchain-ai/langgraphjs

- langgraph/.env.example
- langgraph/src/graph/graph.ts
- langgraph/src/graph/message.ts
- langgraph/src/graph/state.ts
- langgraph/src/tests/pregel.test.ts
- langgraph/src/tests/utils.ts
cc @nfcampos 
porting:
- https://github.com/langchain-ai/langgraph/pull/50
- https://github.com/langchain-ai/langgraph/pull/58
> message graph

- langgraph/src/graph/state.ts
porting https://github.com/langchain-ai/langgraph/pull/61
> patch: Clarify node<>channel name collision error

- langgraph/src/graph/graph.ts
Porting https://github.com/langchain-ai/langgraph/pull/62/
> patch: make conditionalEdgeMapping optional

- langgraph/package.json
> Release 0.0.5

- langgraph/src/graph/graph.ts
- langgraph/src/pregel/index.ts
- langgraph/src/pregel/read.ts
- langgraph/src/pregel/validate.ts
- langgraph/src/tests/pregel.test.ts
- can be replaced with call to .map()
> Remove subscribeToEach

- README.md
- langgraph/src/tests/chatbot.int.test.ts
CC @eyurtsev @nfcampos @bracesproul @hwchase17
> Update quickstart with simpler MessageGraph example

- langgraph/src/channels/any_value.ts
- langgraph/src/channels/binop.ts
- langgraph/src/channels/ephemeral_value.ts
- langgraph/src/channels/last_value.ts
- langgraph/src/channels/named_barrier_value.ts
- langgraph/src/channels/topic.ts
- langgraph/src/graph/graph.ts
- langgraph/src/graph/message.ts
- langgraph/src/graph/state.ts
- langgraph/src/prebuilt/agent_executor.ts
- langgraph/src/prebuilt/chat_agent_executor.ts
- langgraph/src/pregel/index.ts
- langgraph/src/pregel/validate.ts
- langgraph/src/tests/chatbot.int.test.ts
- langgraph/src/tests/graph.test.ts
- langgraph/src/tests/prebuilt.int.test.ts
- langgraph/src/tests/pregel.test.ts
- langgraph/src/tests/tracing.int.test.ts
> Add stricter typings for graph/stategraph/messagegraph constructors

- langgraph/src/channels/any_value.ts
- langgraph/src/channels/base.ts
- langgraph/src/channels/binop.ts
- langgraph/src/channels/ephemeral_value.ts
- langgraph/src/channels/last_value.ts
- langgraph/src/channels/named_barrier_value.ts
- langgraph/src/channels/topic.ts
- langgraph/src/graph/graph.ts
- langgraph/src/graph/message.ts
- langgraph/src/graph/state.ts
- langgraph/src/prebuilt/agent_executor.ts
- langgraph/src/prebuilt/chat_agent_executor.ts
- langgraph/src/pregel/index.ts
- langgraph/src/pregel/io.ts
- langgraph/src/pregel/validate.ts
- langgraph/src/tests/chatbot.int.test.ts
- langgraph/src/tests/graph.test.ts
- langgraph/src/tests/prebuilt.int.test.ts
- langgraph/src/tests/pregel.io.test.ts
- langgraph/src/tests/pregel.test.ts
- langgraph/src/tests/pregel.validate.test.ts
- langgraph/src/tests/tracing.int.test.ts
- still need to migrate StateGraph
> Pregel/Graph: Make channel creation explicit, make Pregel constructor type safe

- langgraph/src/checkpoint/base.ts
- langgraph/src/checkpoint/index.ts
- langgraph/src/checkpoint/memory.ts
- langgraph/src/checkpoint/sqlite.ts
- langgraph/src/graph/graph.ts
- langgraph/src/graph/state.ts
- langgraph/src/index.ts
- langgraph/src/pregel/index.ts
- langgraph/src/serde/base.ts
- Remove 2nd generic from Serializer
- Make Serializer interface more JS-y
- Remove CheckpointAt
> Fix Checkpointer interface

- langgraph/src/graph/graph.ts
- langgraph/src/graph/index.ts
- langgraph/src/graph/state.ts
- langgraph/src/prebuilt/chat_agent_executor.ts
- langgraph/src/pregel/index.ts
- langgraph/src/pregel/io.ts
- langgraph/src/pregel/read.ts
- langgraph/src/pregel/validate.ts
- langgraph/src/pregel/write.ts
- langgraph/src/tests/prebuilt.test.ts
- langgraph/src/tests/pregel.test.ts
- enables more dynamic graphs in the future
- enables conditional edges returning multiple destinations
> Rewrite Graph.compile() to delegate to new CompiledGraph methods

- langgraph/src/checkpoint/base.ts
- langgraph/src/checkpoint/index.ts
- langgraph/src/checkpoint/memory.ts
- langgraph/src/checkpoint/sqlite.ts
- langgraph/src/pregel/index.ts
- langgraph/src/pregel/io.ts
- langgraph/src/tests/checkpoints.test.ts
- langgraph/src/tests/pregel.io.test.ts
- save checkpoints in background
- error checking in pregel class
- fix checkpoint lineage
- fix sqlite checkpointer setup
- fix sqlite checkpointer constructor
> Implement checkpoint metadata

- CONTRIBUTING.md
- langgraph/package.json
- langgraph/src/channels/base.ts
- langgraph/src/checkpoint/base.ts
- langgraph/src/checkpoint/id.ts
- langgraph/src/checkpoint/index.ts
- langgraph/src/checkpoint/memory.ts
- langgraph/src/checkpoint/sqlite.ts
- langgraph/src/graph/graph.ts
- langgraph/src/graph/state.ts
- langgraph/src/index.ts
- langgraph/src/pregel/index.ts
- langgraph/src/pregel/read.ts
- langgraph/src/pregel/write.ts
- langgraph/src/tests/checkpoints.test.ts
- langgraph/src/tests/pregel.test.ts
- langgraph/src/tests/utils.ts
- yarn.lock
- Also rework any objects that will be saved in db / server over api to use snake_case keys (to match py)
> Rename thread_ts to checkpoint_id

- .github/workflows/ci.yml
> Run Node.js 22 in CI

- CONTRIBUTING.md
- langgraph/package.json
- langgraph/src/channels/base.ts
- langgraph/src/channels/dynamic_barrier_value.ts
- langgraph/src/channels/named_barrier_value.ts
- langgraph/src/channels/topic.ts
- langgraph/src/checkpoint/base.ts
- langgraph/src/checkpoint/id.ts
- langgraph/src/checkpoint/index.ts
- langgraph/src/checkpoint/memory.ts
- langgraph/src/checkpoint/sqlite.ts
- langgraph/src/graph/graph.ts
- langgraph/src/graph/state.ts
- langgraph/src/index.ts
- langgraph/src/prebuilt/agent_executor.ts
- langgraph/src/prebuilt/chat_agent_executor.ts
- langgraph/src/pregel/index.ts
- langgraph/src/pregel/read.ts
- langgraph/src/pregel/write.ts
- langgraph/src/tests/chatbot.int.test.ts
- langgraph/src/tests/checkpoints.test.ts
- langgraph/src/tests/pregel.test.ts
- langgraph/src/tests/utils.ts
- yarn.lock
> Support conditional edge from START node

- langgraph/src/channels/base.ts
- langgraph/src/checkpoint/base.ts
- langgraph/src/pregel/debug.ts
- langgraph/src/pregel/index.ts
- langgraph/src/pregel/io.ts
- langgraph/src/pregel/types.ts
- langgraph/src/tests/pregel.io.test.ts
- langgraph/src/tests/pregel.test.ts
> Implement interruptAfter and interruptBefore

- langgraph/package.json
> Release 0.0.13

- langgraph/.gitignore
- langgraph/langchain.config.js
- langgraph/package.json
- langgraph/src/index.ts
- yarn.lock
> Expose checkpoints, remove direct dep on sqlite

- langgraph/package.json
> Release 0.0.14

- langgraph/package.json
> Release 0.0.15

- langgraph/package.json
> Release 0.0.16

- langgraph/package.json
> Release 0.0.17

- langgraph/package.json
> Release 0.0.18

- langgraph/src/graph/graph.ts
- langgraph/src/prebuilt/react_agent_executor.ts
> Raise error if cond edge returns null/missing destination

- langgraph/package.json
> Release 0.0.19

- langgraph/package.json
- langgraph/src/tests/chatbot.int.test.ts
- package.json
- yarn.lock
> Bump ecosystem versions to 0.2.0

- langgraph/package.json
> Release 0.0.21

- langgraph/src/graph/index.ts
- langgraph/src/index.ts
Enables patterns like this:
```ts
let agent: CompiledStateGraph;
export async function call(input: string): Promise<string> {
if (agent === undefined) {
agent = await buildGraph();
}
const res = await agent.invoke({ input });
console.log(res);
return res.agentOutcome.returnValues.output;
}
```
@nfcampos
> Export CompiledStateGraph type

- README.md
- _scripts/run_notebook.py
- docs/Makefile
- docs/_scripts/copy_notebooks.py
- docs/mkdocs.yml
- examples/quickstart.ipynb
Quickstart is essentially the same, though I start with `createReactAgent` to be simpler.
> [Docs] Update README and add Quickstart guide

- docs/docs/index.md
- docs/mkdocs.yml
> [Docs] Update Index

- _scripts/run_notebook.py
- docs/docs/concepts/index.md
Not sure what went wrong when testing
> [Docs] Fix Conceptual Guide

- langgraph/src/channels/base.ts
- langgraph/src/errors.ts
- langgraph/src/pregel/debug.ts
- langgraph/src/pregel/index.ts
- langgraph/src/pregel/io.ts
Fixes #231
Fixes #220
Fixes #180
Fixes #113
CC @andrewnguonly @nfcampos
> Avoid using constructor name check for errors

- langgraph/package.json
- langgraph/src/checkpoint/id.ts
- langgraph/src/tests/checkpoints.test.ts
- yarn.lock
> Fix - Updated uuid pkg to support v6 generation

- docs/mkdocs.yml
> Remove broken edit and view source buttons from docs

- langgraph/package.json
- langgraph/src/constants.ts
- langgraph/src/pregel/index.ts
- langgraph/src/tests/tracing.test.ts
- yarn.lock
> Adds metadata corresponding to the current node to configs

- .github/workflows/ci.yml
- examples/how-tos/respond-in-format.ipynb
> Adds example of how to stream a structured final response from an agent

- langgraph/package.json
- langgraph/src/utils.ts
- package.json
- yarn.lock
> Update conditional edge tracing for new core version

- README.md
- langgraph/README.md
I was very familiar with Jupyter notebooks but hadn't used tslab before. Took me a minute to figure out how to run the examples. This may not be the best approach, but got me up and running and thought it might help someone else.
> tslab instructions - Update README.md

- docs/docs/tutorials/index.md
- docs/mkdocs.yml
> Add quickstart to tutorials

- langgraph/src/pregel/index.ts
- langgraph/src/tests/prebuilt.test.ts
- langgraph/src/tests/utils.ts
> Adds signal test, fix bug

- langgraph/src/graph/index.ts
- langgraph/src/graph/state.ts
- langgraph/src/web.ts
> Export Annotation etc from root

- langgraph/package.json
> Release 0.0.33

- langgraph/.eslintrc.cjs
- langgraph/package.json
- langgraph/src/graph/annotation.ts
- langgraph/src/graph/index.ts
- langgraph/src/graph/message.ts
- langgraph/src/graph/state.ts
- langgraph/src/tests/graph.test.ts
- langgraph/src/tests/pregel.test.ts
- yarn.lock
```ts
// useful to generate SQL query
const modelLowTemp = new ChatOpenAI({ temperature: 0.1 });
// useful to generate natural language outputs
const modelHighTemp = new ChatOpenAI({ temperature: 0.7 });
const annotation = Annotation.Root({
messages: Annotation({ reducer: messagesStateReducer, default: () => [] }),
user_query: Annotation<string>(),
sql_query: Annotation<string>(),
sql_explanation: Annotation<string>(),
});
const generatePrompt = new SystemMessage(
"You are a helpful data analyst, who generates SQL queries for users based on their questions."
);
async function generateSql(state: typeof annotation.State) {
const userMessage = new HumanMessage(state.user_query);
const messages = [generatePrompt, ...state.messages, userMessage];
const res = await …
```
> Add Annotation.Root to make it easier to access State, Update and Node types

- langgraph/src/graph/graph.ts
> feat(types): expose node type, run input and run output in compiled graph

- langgraph/src/graph/index.ts
- langgraph/src/web.ts
> feat(types): export CompiledGraph

- langgraph/src/pregel/index.ts
- langgraph/src/tests/pregel.test.ts
- langgraph/src/tests/utils.ts
> feat(pregel): add support for multiple stream modes

- langgraph/src/channels/any_value.ts
- langgraph/src/channels/base.ts
- langgraph/src/channels/binop.ts
- langgraph/src/channels/dynamic_barrier_value.ts
- langgraph/src/channels/ephemeral_value.ts
- langgraph/src/channels/last_value.ts
- langgraph/src/channels/named_barrier_value.ts
- langgraph/src/channels/topic.ts
- langgraph/src/checkpoint/base.ts
- langgraph/src/checkpoint/serde/types.ts
- langgraph/src/constants.ts
- langgraph/src/graph/graph.ts
- langgraph/src/graph/state.ts
- langgraph/src/pregel/algo.ts
- langgraph/src/pregel/index.ts
- langgraph/src/pregel/loop.ts
- langgraph/src/tests/channels.test.ts
- langgraph/src/tests/pregel.test.ts
> Update channel base class, fix checkpointer error handling in loop

- langgraph/src/pregel/algo.ts
- langgraph/src/pregel/debug.ts
- langgraph/src/pregel/io.ts
- langgraph/src/pregel/loop.ts
- langgraph/src/pregel/types.ts
- langgraph/src/tests/pregel.test.ts
- langgraph/src/tests/utils.ts
> feat(debug): add checkpoint debug events

- docs/docs/concepts/low_level.md
> docs[patch]: Fix state def in low level concepts doc

- libs/checkpoint-sqlite/src/index.ts
- libs/checkpoint/src/base.ts
- libs/checkpoint/src/memory.ts
- libs/checkpoint/src/serde/base.ts
- libs/checkpoint/src/serde/jsonplus.ts
- libs/checkpoint/src/serde/tests/jsonplus.test.ts
- libs/langgraph/src/tests/utils.ts
Need to be careful about bumping versions
> Update checkpoint serde to support types

- docs/docs/concepts/low_level.md
> Remove unsupported docs for now

- libs/langgraph/package.json
- libs/langgraph/src/tests/pregel.test.ts
- yarn.lock
> chore(pregel): add test for `getGraph().toJSON()`

- libs/langgraph/src/channels/binop.ts
- libs/langgraph/src/channels/index.ts
- libs/langgraph/src/graph/index.ts
- libs/langgraph/src/web.ts
> langchain[patch]: Export types to fix portability issues

- libs/checkpoint/src/base.ts
- libs/checkpoint/src/tests/checkpoints.test.ts
- libs/langgraph/src/pregel/algo.ts
- libs/langgraph/src/pregel/index.ts
> checkpoint[patch]: Fix checkpointer generic

- libs/checkpoint/src/base.ts
- libs/checkpoint/src/tests/checkpoints.test.ts
> feat(checkpoint): rely on string comparison instead

- libs/langgraph/src/graph/graph.ts
- libs/langgraph/src/prebuilt/react_agent_executor.ts
- libs/langgraph/src/tests/pregel.test.ts
> langgraph[patch]: Fix typing for conditional edge array route maps

- examples/quickstart.ipynb
- libs/langgraph/src/prebuilt/tool_node.ts
- libs/langgraph/src/tests/prebuilt.test.ts
Reverts langchain-ai/langgraphjs#404
> Revert "langgraph[patch]: Relax tool node generic requirement"

- libs/langgraph/src/channels/any_value.ts
- libs/langgraph/src/channels/dynamic_barrier_value.ts
- libs/langgraph/src/channels/index.ts
- libs/langgraph/src/channels/last_value.ts
- libs/langgraph/src/channels/named_barrier_value.ts
- libs/langgraph/src/web.ts
> langgraph[patch]: Export all channel types for portability

- libs/langgraph/src/channels/dynamic_barrier_value.ts
- libs/langgraph/src/channels/ephemeral_value.ts
- libs/langgraph/src/channels/last_value.ts
- libs/langgraph/src/channels/named_barrier_value.ts
- libs/langgraph/src/channels/topic.ts
- libs/langgraph/src/graph/index.ts
- libs/langgraph/src/web.ts
Tested on an RC
@hinthornw @bracesproul
> langgraph[patch]: Export more internal types for portability

- libs/langgraph/src/graph/graph.ts
- libs/langgraph/src/tests/pregel.test.ts
Is it really so simple?
@hinthornw
> langgraph[patch]: Allow dead-end nodes

- docs/mkdocs.yml
> docs: Adds LangGraph Cloud link to docs

- libs/langgraph/src/pregel/loop.ts
- libs/langgraph/src/tests/pregel.test.ts
Port of https://github.com/langchain-ai/langgraph/pull/1550/
> feat: Remove the need to fork a thread to replay a past state

- libs/langgraph/src/pregel/loop.ts
- libs/langgraph/src/tests/pregel.test.ts
Port of https://github.com/langchain-ai/langgraph/pull/1545
> fix: For input checkpoint use filtered input writes in checkpoint metadata

- examples/how-tos/configuration.ipynb
- libs/langgraph/src/graph/state.ts
- libs/langgraph/src/pregel/index.ts
- libs/langgraph/src/pregel/types.ts
- libs/langgraph/src/tests/pregel.test.ts
> feat: Adds config schema support

- libs/langgraph/src/managed/base.ts
- libs/langgraph/src/pregel/index.ts
- libs/langgraph/src/tests/pregel.test.ts
> fix(langgraph): Fix bug in getting state with managed values

- libs/checkpoint/src/serde/jsonplus.ts
- libs/checkpoint/src/serde/tests/jsonplus.test.ts
- libs/checkpoint/src/serde/utils/fast-safe-stringify/LICENSE
- libs/checkpoint/src/serde/utils/fast-safe-stringify/index.ts
> fix(checkpoint): Fix overzealous circular reference detection in checkpointers

- libs/langgraph/src/graph/graph.ts
- libs/langgraph/src/graph/state.ts
- libs/langgraph/src/pregel/index.ts
- libs/langgraph/src/pregel/types.ts
Trying to get the stream output types narrowed
> Some plumbing for a narrower stream output

- libs/langgraph/package.json
- yarn.lock
> chore(langgraph): Bump deps, rc version

- libs/langgraph/src/pregel/utils/config.ts
- libs/langgraph/src/tests/prebuilt.test.ts
> fix: Fix callback manager propagation issues

- libs/langgraph/src/pregel/index.ts
- libs/langgraph/src/tests/pregel.slow_checkpointer.int.test.ts
- libs/langgraph/src/tests/pregel.test.ts
- libs/langgraph/src/tests/utils.ts
> fix: Fix checkpointer race condition

- libs/langgraph/src/graph/state.ts
- libs/langgraph/src/tests/pregel.test.ts
> fix(langgraph): Pass full state properties to conditional edges

- libs/langgraph/package.json
- libs/langgraph/src/graph/graph.ts
- libs/langgraph/src/graph/state.ts
- libs/langgraph/src/pregel/index.ts
- yarn.lock
> feat(langgraph): Add type hints for configurable field if config schema is passed

- libs/langgraph/package.json
- libs/langgraph/src/web.ts
- yarn.lock
> fix(langgraph): Fix broken export version

- libs/langgraph/src/prebuilt/index.ts
- libs/langgraph/src/prebuilt/tool_node.ts
- libs/langgraph/src/web.ts
> fix(langgraph): Make subclassing ToolNode easier

- libs/checkpoint/src/base.ts
> Fix docstring for Checkpoint.v

- examples/package.json
- libs/langgraph/package.json
- libs/langgraph/src/graph/graph.ts
- libs/langgraph/src/graph/state.ts
- libs/langgraph/src/prebuilt/react_agent_executor.ts
- libs/langgraph/src/prebuilt/tool_node.ts
- libs/langgraph/src/pregel/index.ts
- libs/langgraph/src/pregel/read.ts
- libs/langgraph/src/pregel/write.ts
- libs/langgraph/src/tests/prebuilt.test.ts
- libs/langgraph/src/tests/pregel.test.ts
- libs/langgraph/src/tests/tracing.test.ts
- libs/langgraph/src/utils.ts
- yarn.lock
Before:
https://smith.langchain.com/public/76a7e0df-2ecd-4041-bc7b-6941fe1199ec/r
After:
https://smith.langchain.com/public/1fb20156-e7b8-4494-987f-5fad33c391d4/r
> feat(langgraph): Clean up traces 

- libs/langgraph/package.json
- libs/langgraph/src/pregel/remote.ts
- yarn.lock
> feat(remote): upstream type casts from remote to SDK

- README.md
- libs/langgraph/README.md
Fix a broken link in the documentation.
> fix(docs): Update broken dynamic tool link

- libs/checkpoint/src/types.ts
- libs/langgraph/src/pregel/index.ts
> Add update state branch for copy

- libs/langgraph/package.json
> Release 0.2.22

- libs/checkpoint/src/base.ts
- libs/checkpoint/src/serde/types.ts
- libs/langgraph/src/constants.ts
- libs/langgraph/src/errors.ts
- libs/langgraph/src/interrupt.ts
- libs/langgraph/src/pregel/algo.ts
- libs/langgraph/src/pregel/index.ts
- libs/langgraph/src/pregel/io.ts
- libs/langgraph/src/pregel/loop.ts
- libs/langgraph/src/pregel/retry.ts
- libs/langgraph/src/tests/pregel.test.ts
- libs/langgraph/src/web.ts
> Implement interrupt(...) and Command({resume: ...})

- docs/docs/concepts/low_level.md
- docs/docs/how-tos/index.md
- docs/mkdocs.yml
- examples/how-tos/command.ipynb
> docs: Add command docs

- libs/langgraph/package.json
- libs/langgraph/src/pregel/loop.ts
- yarn.lock
Bumped langgraph checkpoint dep to latest, always add to checkpointer
> fix(langgraph): Put writes for special channels

- libs/langgraph/src/pregel/index.ts
- libs/langgraph/src/pregel/io.ts
- libs/langgraph/src/pregel/loop.ts
- libs/langgraph/src/tests/pregel.test.ts
> fix(langgraph): Fix Command update behavior for static breakpoints

- libs/langgraph/src/graph/graph.ts
- libs/langgraph/src/graph/state.ts
- libs/langgraph/src/tests/pregel.test.ts
> fix(langgraph): Fix state graph invoke typing

- docs/docs/how-tos/index.md
- docs/docs/troubleshooting/errors/UNREACHABLE_NODE.ipynb
- docs/docs/troubleshooting/errors/index.md
- docs/mkdocs.yml
- examples/how-tos/command.ipynb
- libs/langgraph/src/constants.ts
- libs/langgraph/src/errors.ts
- libs/langgraph/src/graph/graph.ts
> feat(langgraph): Adds error page for unreachable nodes

- libs/langgraph/src/pregel/io.ts
> fix(io): update tuples are ignored by pregel io

- docs/docs/concepts/langgraph_cli.md
> feat(docs): add updated CLI command

- docs/docs/concepts/langgraph_cli.md
> docs: add up command for the JS CLI

- README.md
- libs/langgraph/README.md
Align with python docs:
- Adds "Why LangGraph"
- Links to quickstart
- Adds content on LangGraph Platform
> docs: update readme and landing page

- .github/workflows/ci.yml
- README.md
- libs/langgraph/README.md
> docs: Update LangGraph.js READMEs

- examples/rag/langgraph_agentic_rag.ipynb
Fixes https://github.com/langchain-ai/langgraphjs/issues/807
> docs: fix a broken link

- docs/.gitignore
- docs/Makefile
- docs/docs/concepts/assistants.md
- docs/docs/concepts/deployment_options.md
- docs/docs/concepts/double_texting.md
- docs/docs/concepts/langgraph_cli.md
- docs/docs/concepts/langgraph_cloud.md
- docs/docs/concepts/langgraph_server.md
- docs/docs/concepts/sdk.md
- docs/docs/how-tos/index.md
- docs/docs/tutorials/deployment.md
- docs/docs/tutorials/index.md
- docs/docs/tutorials/langgraph-platform/local-server.md
- docs/mkdocs.yml
> docs: Pull LangGraph Cloud docs on build, update cloud and local server guides

- libs/langgraph/src/func/types.ts
See comments in code for explanation.
> fix task/entrypoint func type

- docs/_scripts/third_party/packages.yml
placeholder for third party libraries written using langgraph js
> docs: third party packages.yml

- docs/Makefile
- docs/_scripts/generate_llms_text.py
- docs/_scripts/notebook_hooks.py
Isn't hooked up to the github workflow yet
> generate llms-text

- .github/workflows/deploy_docs.yml
> ci: add llms-text

- docs/mkdocs.yml
> chore(docs): fix measurement id

- libs/langgraph/src/tests/pregel.test.ts
Adds test to ensure that the case demonstrated in [this doc](https://langchain-ai.github.io/langgraphjs/how-tos/command/#navigating-to-a-node-in-a-parent-graph) doesn't regress.
> chore(langgraph): add regression test for PARENT Command

- libs/langgraph/src/pregel/io.ts
- libs/langgraph/src/pregel/loop.ts
- libs/langgraph/src/pregel/runner.ts
- libs/langgraph/src/tests/pregel.test.ts
Ports langchain-ai/langgraph#3134
> feat(langgraph): send subgraph state to parent when using Command.PARENT

- docs/docs/concepts/functional_api.md
- docs/docs/concepts/index.md
- docs/docs/how-tos/index.md
- libs/langgraph/src/func/index.ts
Remove the beta tag from the functional API
> remove beta from functional api

- libs/langgraph/src/prebuilt/react_agent_executor.ts
- libs/langgraph/tsconfig.json
> fix(prebuilt): honor user provided state schema

- docs/docs/concepts/low_level.md
> fix(docs): fix broken example in low_level.md

- docs/docs/concepts/low_level.md
Clarifies annoying boilerplate in example.
> chore(docs): small clarifying comment in low_level.md

- libs/langgraph-supervisor/tsconfig.cjs.json
- libs/langgraph-supervisor/tsconfig.json
> fix(supervisor): actually output CJS in CJS build

- libs/langgraph/src/index.ts
- libs/langgraph/src/pregel/utils/config.ts
> feat(langgraph): export getConfig helper fn

- libs/langgraph/src/prebuilt/react_agent_executor.ts
- libs/langgraph/src/tests/prebuilt.test.ts
- libs/langgraph/src/tests/utils.ts
> feat(langgraph): support model.bindTools in createReactAgent for google genai

- docs/docs/concepts/human_in_the_loop.md
- docs/docs/concepts/low_level.md
- docs/docs/concepts/streaming.md
- docs/docs/how-tos/index.md
- docs/mkdocs.yml
- examples/how-tos/recursion-limit.ipynb
- examples/how-tos/wait-user-input-functional.ipynb
- examples/how-tos/wait-user-input.ipynb
- libs/langgraph/src/interrupt.ts
> docs: Add missing glossary section, recursion limit guide, caveats to interrupt() function, fix broken links

- CONTRIBUTING.md
Fixes a broken link and int testing command
> fix(docs): update integration testing instructions

- docs/docs/llms.txt
> feat(docs): add llms.txt

- libs/langgraph-cua/package.json
- libs/langgraph-cua/src/index.ts
- libs/langgraph-cua/src/nodes/call-model.ts
- libs/langgraph-cua/src/nodes/create-vm-instance.ts
- libs/langgraph-cua/src/nodes/take-computer-action.ts
- libs/langgraph-cua/src/types.ts
- libs/langgraph-cua/src/utils.ts
- yarn.lock
Added args to the `createCua` function for passing node funcs which execute before and after taking an action
> fix(cua): Add execute before and after nodes

- libs/langgraph/package.json
> release(langgraph): 0.2.59

- libs/langgraph/src/constants.ts
- libs/langgraph/src/tests/constants.test.ts
- libs/langgraph/src/tests/python_port/graph_structure.test.ts
- libs/langgraph/src/tests/remote.test.ts
> fix(langgraph): handle cycles correctly on Command/Send deserialization

- libs/langgraph/src/graph/zod/index.ts
> fix(langgraph): do not show side-effect warning for zod entrypoint

- docs/docs/llms-txt-overview.md
> docs: update llms overview

- libs/langgraph/src/prebuilt/react_agent_executor.ts
Fixes https://github.com/langchain-ai/langgraphjs/issues/993
> fix(prebuilt): make sure the AIMessage mutation occurs within `lc_kwargs` as well

- libs/langgraph/src/pregel/messages.test.ts
- libs/langgraph/src/pregel/runner.test.ts
- libs/langgraph/src/pregel/validate.test.ts
> Add tests (w claude) for pregel/messages, pregel/runner, pregel/validate

- examples/how-tos/react-memory.ipynb
Fixes # 
remove content duplicate "the same the same" in docs
Link: [docs](https://langchain-ai.github.io/langgraphjs/how-tos/react-memory/#usage)
> remove content duplicate of "the same the same" in docs

- libs/langgraph-cua/README.md
Typo fix in CUA prebuilt agent readme.
> docs(cua): Fix readme typo

- docs/docs/tutorials/workflows/index.md
> docs: remove one more beta

- libs/langgraph/src/func/index.ts
- libs/langgraph/src/graph/graph.ts
- libs/langgraph/src/pregel/call.ts
- libs/langgraph/src/tests/func.test.ts
- libs/langgraph/src/tests/python_port/graph_structure.test.ts
> fix(langgraph): fix updateState for functional API

- libs/langgraph/src/pregel/index.ts
- libs/langgraph/src/tests/func.test.ts
> Implement updateState for entrypoint/task

- docs/mkdocs.yml
- docs/overrides/partials/integrations/analytics/google.html
> docs: Adds additional Google Analytics tag to docs

- libs/langgraph/src/tests/pregel.test.ts
Nails down behavior that two updates are expected in this case
> chore(langgraph): Adds test case for Command.PARENT update behavior

- libs/langgraph/src/channels/any_value.ts
- libs/langgraph/src/channels/binop.ts
- libs/langgraph/src/channels/dynamic_barrier_value.ts
- libs/langgraph/src/channels/ephemeral_value.ts
- libs/langgraph/src/channels/last_value.ts
- libs/langgraph/src/channels/named_barrier_value.ts
- libs/langgraph/src/channels/topic.ts
- libs/langgraph/src/tests/channels.test.ts
- libs/langgraph/src/tests/pregel.test.ts
> fix(langgraph): allow restoring falsy values from channels

- libs/langgraph/src/graph/state.ts
- libs/langgraph/src/tests/zod_state.test.ts
> feat(langgraph): allow zod schemas in node input opts

- docs/docs/concepts/low_level.md
- libs/langgraph/src/graph/messages_annotation.ts
- libs/langgraph/src/tests/prebuilt.test.ts
- libs/langgraph/src/web.ts
Adds a zod-based graph state utility that mimics `MessagesAnnotation`
> feat: `MessagesZodSchema`

- libs/langgraph/src/graph/state.ts
- libs/langgraph/src/tests/pregel.test.ts
- libs/langgraph/src/tests/tracing.test.ts
Port of https://github.com/langchain-ai/langgraph/pull/4064
> feat(langgraph): reduce number of branches

- libs/langgraph/src/pregel/runner.ts
Requirement for porting https://github.com/langchain-ai/langgraph/pull/3907
> chore(langgraph): split `call` method from `executeTasksWithRetry`

- libs/langgraph/src/graph/state.ts
- libs/langgraph/src/graph/zod/schema.ts
- libs/langgraph/src/graph/zod/state.ts
- libs/langgraph/src/tests/pregel.test-d.ts
Also adds additional tests for `pregel.test-d.ts`
> fix(langgraph): apply Zod reducer when attempting to validate input

- libs/langgraph-swarm/package.json
- yarn.lock
Relax `peerDependencies` constraint to support `@langchain/langgraph 0.3.x`
> release(swarm): 0.0.4

- libs/langgraph/src/prebuilt/react_agent_executor.ts
- libs/langgraph/src/tests/prebuilt.test.ts
- libs/langgraph/src/tests/utils.ts
Port of https://github.com/langchain-ai/langgraph/pull/4800
> feat(langgraph): add support for built-in tools in prebuilts

- docs/overrides/main.html
> revert incident banner

- environment_tests/test-exports-tsc/package.json
- environment_tests/test-exports-tsc/src/main.ts
- environment_tests/test-exports-tsc/src/zod.ts
- environment_tests/test-exports-tsc/tsconfig.json
- libs/langgraph/src/graph/zod/index.ts
> patch(langgraph): fix missing zod export

- examples/quickstart.ipynb
> fix(docs): nudge folks to use ESM in quickstart

- libs/langgraph/src/graph/state.ts
- libs/langgraph/src/pregel/index.ts
- libs/langgraph/src/pregel/loop.ts
- libs/langgraph/src/pregel/types.ts
- libs/langgraph/src/tests/pregel.test.ts
Port of https://github.com/langchain-ai/langgraph/pull/3055
> feat(langgraph): add support for checkpointer: true

- docs/overrides/main.html
> docs: Academy banner

- libs/langgraph/src/pregel/index.ts
- libs/langgraph/src/tests/pregel.test.ts
Closes https://github.com/langchain-ai/langgraphjs/issues/1116
> fix(langgraph): respect streamMode when invoking subgraph in a node

- examples/multi_agent/multi_agent_collaboration.ipynb
- Add setup section in multi agent collaboration
- Fix tavily deprecated warning
> doc: multi agent collaboration. fix tavily and setup

- examples/multi_agent/hierarchical_agent_teams.ipynb
- Fix Deprecated Tavily
- Fix Deprecated JsonOutputToolsParser
- Fix Runnable Pipe for Authoring
- Add Runnable Pipe for research
- Fix Authoring graph Reasearch Team Node
> docs: Fix Issues with Hierarchical tutorial

- .changeset/fluffy-deer-wonder.md
- libs/langgraph/package.json
- libs/langgraph/src/pregel/loop.ts
- libs/langgraph/src/tests/pregel.test.ts
Mirror https://github.com/langchain-ai/langgraph/blob/579c7831b915d7e596d612333da4b94be7000c72/libs/langgraph/langgraph/pregel/loop.py#L585
> feat: Exactly once for run ID resuming

- .changeset/silly-webs-lie.md
- libs/langgraph-api/src/stream.mts
- libs/langgraph-api/tests/api.test.mts
Port of https://github.com/langchain-ai/langgraph-api/pull/827
> fix(api): apply namespace to messages-tuple stream mode

- README.md
also does a prettier format pass on readme
> chore: add forum to readme

- .changeset/whole-dots-retire.md
- libs/langgraph/src/graph/messages_annotation.ts
- libs/langgraph/src/graph/zod/meta.ts
- libs/langgraph/src/graph/zod/zod-registry.ts
- libs/langgraph/src/tests/zod_state.test-d.ts
- libs/langgraph/src/web.ts
Also add tests for Zod 3, 4 and 4 mini.
> feat(langgraph): add UpdateType type utility for Zod, improve Zod 4 and Zod 4 mini support

- .changeset/fifty-sloths-try.md
- .changeset/fluffy-toes-give.md
- .changeset/proud-terms-take.md
- libs/langgraph-api/src/api/assistants.mts
- libs/langgraph-api/src/api/runs.mts
- libs/langgraph-api/src/graph/load.mts
- libs/langgraph-api/src/schemas.mts
- libs/langgraph-api/src/storage/ops.mts
- libs/langgraph-api/src/stream.mts
- libs/langgraph-api/tests/api.test.mts
- libs/langgraph-api/tests/graphs/langgraph.json
- libs/langgraph-api/tests/graphs/simple_runtime.mts
- libs/langgraph/src/graph/graph.ts
- libs/langgraph/src/graph/state.ts
- libs/langgraph/src/pregel/index.ts
- libs/langgraph/src/pregel/remote.ts
- libs/langgraph/src/pregel/runnable_types.ts
- libs/langgraph/src/pregel/types.ts
- libs/langgraph/src/pregel/utils/config.ts
- libs/langgraph/src/tests/pregel.test-d.ts
- libs/langgraph/src/tests/utils.ts
- libs/langgraph/src/web.ts
- libs/sdk/src/auth/types.ts
- libs/sdk/src/client.ts
- libs/sdk/src/schema.ts
- libs/sdk/src/types.ts
Mostly semantics, with the main improvement being avoidance of mixing internal configurable fields with user-defined context.
> chore(langgraph): context API port

- .changeset/easy-bats-end.md
- libs/sdk/src/schema.ts
> fix: update assistant interface to include context

- .changeset/slow-tigers-help.md
- libs/langgraph-api/src/api/meta.mts
- libs/langgraph-api/src/server.mts
> chore(api): add installed langgraph version to js server

- .changeset/vast-flowers-yawn.md
- libs/langgraph/src/pregel/remote.ts
- libs/langgraph/src/tests/remote.test.ts
Closes RemoteGraph recursion loop #1446
> fix(langgraph): fix invalid safe serialization of RunnableConfig for RemoteGraph

- .changeset/supervisor-params.md
- libs/langgraph-supervisor/src/supervisor.ts
> feat(supervisor): support contextSchema in supervisor

- .changeset/cold-walls-burn.md
- libs/langgraph/src/prebuilt/react_agent_executor.ts
- libs/langgraph/src/prebuilt/tool_node.ts
- libs/langgraph/src/tests/prebuilt.test.ts
Mimics the work done in https://github.com/langchain-ai/langgraph/pull/3126.
> feat(langgraph): use Send for each of the tool calls

- .changeset/brave-rings-mate.md
- libs/langgraph-api/src/api/runs.mts
- libs/langgraph-api/tests/api.test.mts
> fix(api): send Content-Location header for stateless runs

- docs/docs/concepts/plans.md
- docs/docs/concepts/self_hosted.md
Description: updates sales team links to point to our form.
Issue: DOC-170 (internal Linear ticket)
> Update sales links

- .changeset/fruity-cows-relate.md
- libs/langgraph-cua/package.json
- libs/langgraph-supervisor/package.json
- libs/langgraph-swarm/package.json
- yarn.lock
Reverts langchain-ai/langgraphjs#1584
> Revert "chore: bump peer ranges to V1.0.0"

- docs/docs/concepts/low_level.md
- examples/how-tos/define-state.ipynb
> fix(docs): quick docs update for Zod 4 changes

- .changeset/clean-meals-agree.md
- .changeset/weak-phones-grab.md
- libs/sdk/src/react/manager.ts
- libs/sdk/src/react/stream.custom.tsx
- libs/sdk/src/react/stream.lgp.tsx
- libs/sdk/src/react/thread.tsx
- libs/sdk/src/react/types.tsx
> fix(sdk): useStream keeping stale thread history when switching during stream, no cancel when disconnecting resumable stream

- .changeset/fluffy-otters-matter.md
- libs/langgraph/src/graph/index.ts
> fix(@langchain/langgraph): export missing symbol
